content: "@HOME/Desktop"
servers:
    sia:
        uri: 10.10.112.20
        user: acc-server-admin
        password: shwsa3nn
        description: experimental kubernetes server
        path-prefix: SIA/sia-system/configuration

    devel:
        uri: 10.10.112.21
        user: acc-server-admin
        password: shwsa3nn
        description: application server based on Docker and jee
        path-prefix: SIA-NEXT/sia-system/configuration
